### ISSUE TITLE
Support Bitcoin chain using pre-signed schemes

### ISSUE THREAD

**Issue by tiero** [ark-network/ark#147]
To be researched the support additional chains and additional wallet backends. (BDK rust instance over gRPC, embedded btcsuite or LND wallet over gRPC?). 

RPC may be a bit different and Ruben shortcut is necessary to enable offline receiving.

**Comment by louisinger** [comment]
- [ ] pre-signed congestion tree and `TxBuilder` interface #178 
- [ ] handle tree signatures in finalization stage (application).
- [ ] add new RPCs letting to (1) send nonces, (2) receive aggregated nonces and (3) send signatures.
- [ ] bitcoin CLI (different pkg ?)

**Comment by louisinger** [comment]
closed by https://github.com/ark-network/ark/pull/271
