### ISSUE TITLE
Return swept timestamp instead

### ISSUE THREAD

**Issue by bordalix** [ark-network/ark#170]
Today, `/v1/vtxos/<ark address>` returns a boolean `swept` to inform if the VTXO was swept by the ASP.

In order for the client to properly know when this swept occurred, it would be better to return a unix timestamp instead (and 0 if is not swept).

@louisinger do you think is possible/easy to make this change?

**Comment by bordalix** [comment]
An alternative solution would be for `expireAt` to keep its previous value (before it was swept).
This way the wallet could know when was this VTXO swept.
Otherwise the wallet will always show "Just now".

<img width="1000" alt="Screenshot 2024-05-22 at 10 28 29" src="https://github.com/ark-network/ark/assets/9318412/549cbe93-dd82-4956-a354-7d52846b8ed5">

**Comment by tiero** [comment]
Agreed!
