### ISSUE TITLE
GetRound takes 19 seconds

### ISSUE THREAD

**Issue by bordalix** [ark-network/ark#179]
Possible related to #177 

The following query (on testnet) takes about 19 seconds to return.

```
curl 'https://asp.arkdev.info/v1/round/c4ec2fc62a8fd8ba70768169cb04909e57bc584e249341557a3f0cded52f4d90' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,pt;q=0.8,la;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: http://localhost:3001' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: http://localhost:3001/' \
  -H 'sec-ch-ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
 ```

**Comment by bordalix** [comment]
> @bordalix we migrated the db used by the ASP to sqlite, the issue should be fixed, can you double-check?

@altafan I'm getting internal server error when replaying the curl command above, or even with a simple query to the actual round:

```
$ curl 'https://asp.arkdev.info/v1/round'
Internal Server Error
```

**Comment by bordalix** [comment]
Everything seems to be working fine now.

Having said that, it seems if have a new behaviour (notice the trailing slash on the url)

```
$ curl 'https://asp.arkdev.info/v1/round'

{"code":5, "message":"Not Found", "details":[]}
```

```
$ curl 'https://asp.arkdev.info/v1/round/'

{"round":{"id":"7c0c742b-137a-4d70-a665-948fa00cf94b", "start":"1719225736", "end":"0", "poolTx":"", "congestionTree":{"levels":[]}, "forfeitTxs":[], "connectors":[]}}
```

**Comment by tiero** [comment]
@altafan @louisinger

**Comment by altafan** [comment]
we didn't really change anything, are you 100% sure the behavior was different before?

**Comment by bordalix** [comment]
> we didn't really change anything related to grpc-gateway, are you 100% sure the behavior was different before?

No, not 100% sure.

**Comment by bordalix** [comment]
UPDATE: tested with commits way back in time, and the behaviour was the same.
False alarm, move on, nothing to see here.

**Comment by altafan** [comment]
Thanks for the verification.
