### ISSUE TITLE
Bitcoin wallet

### ISSUE THREAD

**Issue by altafan** [ark-network/ark#182]
Let's implement a bitcoin implementation of [`ports.WalletService`](https://github.com/ark-network/ark/blob/master/server/internal/core/ports/wallet.go#L9) as single-key wallet.

Actually 2 keys, one for the ark account and one for the ark-connector account.

As a single-key wallet, we don't need to persist utxos/txs as it's affordable to restore them at startup and not slow down the bitcoin version's development.

**Comment by tiero** [comment]
Cant' we use btcwallet out of the box? We may need some RPC to create/restore wallet (but those where steps needed also with Ocean)
