### ISSUE TITLE
new payments API

### ISSUE THREAD

**Issue by altafan** [ark-network/ark#183]
Let's add the APIs for the shortcut so users don't need to join rounds to make off-chain payments.

Instead, receivers will settle their "shortcut vtxos" as soon as they get back online and fetch them from the explorer (ASP).

This way the users would need to join rounds only to (collaboratively) exit or to send to themselves.

**Comment by tiero** [comment]
I am thinking of

- CreateShortcutPayment
- ClaimShortcutPayment

Altough I feel more oriented to Async rather than Shortcut. The former is more user-oriented, the latter more implementer/low-lever oriented.

**Comment by altafan** [comment]
I'd go for:
```
rpc CreateAsyncPayment(CreateAsyncPaymentRequest) returns (CreateAsyncPaymentResponse)
rpc CompleteAsyncPayment(CompleteAsyncPaymentRequest) returns (CompleteAsyncPaymentResponse)

message CreateAsyncPaymentRequest {
   // option A: the shortcut is created client-side, the asp just signs it
   string shortcut_tx = 1;
   // option B: the shorcut is created and signed by the asp
   string receiver_pubkey = 1;
   Vtxo input = 2;
}

message CreateAsyncPaymentResponse {
   string signed_tx = 1;
    // with option B: the asp could create the forfeit tx for the sender
   string forfeit_tx = 2;
}

message CompleteAsyncPaymentRequest {
    string signed_shortcut_tx = 1;
    string signed_forfeit_tx = 2;
}
```

Not sure we need a dedicated RPC for the receiver, since he just needs to join a round to settle the vtxo, which can be done with the existing rpcs already.

**Comment by tiero** [comment]
I would go with Option B, to make the client do less work.

> Not sure we need a dedicated RPC for the receiver

Uhm the advantage of dedicated RPC is that we dont need to have aflag to indicate if the VTXO to be registered, if is a "shortcut VTXO" or a "normal one". Single Resposibility.
