### ISSUE TITLE
Client SDK

### ISSUE THREAD

**Issue by altafan** [ark-network/ark#192]
We want to create a reusable library that clients can consume for interaction with the ASP.

The idea is to move (most of) the code within the CLI commands to a standalone package that can then be imported into other client wallet projects.

Let's provide both grpc and rest clients.

**Comment by sekulicd** [comment]
We move this to /root/pkg/client or smtn?

**Comment by tiero** [comment]
We have a client,server,common structure with a monorepo. Not sure what's best, to have pkg in root or inside client?

**Comment by sekulicd** [comment]
> We have a client,server,common structure with a monorepo. Not sure what's best, to have pkg in root or inside client? 
> 
> 
> What's your suggestion?

IMO /root/pkg

**Comment by altafan** [comment]
I think in this case it's better to have pkg in `common/client-sdk` so we don't import anything from `server`

**Comment by tiero** [comment]
I think it is best to have it at root. A dedicated top-level directory makes it clear that it is a standalone module intended for external use, not just an internal component tied to common. It is more easily discoverable by developers who need to use the SDK. Moreover it allows the SDK to evolve independently from other components of the monorepo.


```
monorepo-root/
├── client/
│   └── ...
├── server/
│   └── ...
├── common/
│   └── ...
└── pkg/
    └── client-sdk/
        ├── example.go
        └── ...
```

**Comment by altafan** [comment]
The sdk will import stubs from `server/api-spec/`. Following your reasoning, maybe it makes sense to move `api-spec/` (and stuff related to buf) to root too?

**Comment by tiero** [comment]
Yes, good idea, as is a shared resource between client/sever anyway

**Comment by tiero** [comment]
@sekulicd also make sure to design the SDK to be easy to compile to WebAssembly, ie. exporting a JS glue that calls the Public APIs of the Go package, also from the browser.

**Comment by tiero** [comment]
> In JS, the second one would be used

We do lose the code-gen if the client SDK (in wasm targets) have to use JSON endpoints?

**Comment by sekulicd** [comment]
> the idea is to have a client that consumes either grpc or rest endpoints. In JS, the second one would be used 

i understood we wanted to give all options to the clients(grpc, rest, grpcweb), clients(browser) lose option to use grpc from js if we only support above options

**Comment by tiero** [comment]
after quick chat offline, is not worth to introduce gRPC-web complexity as we have already gRPC Gateway and we have a way to automatically generate client code once we change Proto/Swagger
