### ISSUE TITLE
Taproot descriptor with 1 leaf is not parsable by bitcoin-core

### ISSUE THREAD

**Issue by louisinger** [ark-network/ark#367]
This is the current desriptor string returned by our parser in case of 1 leaf only
```
"tr(INTERNAL_KEY ,{pk(KEY)})"
```
the "{ }" brackets are not expected by bitcoin core, the correct descriptor should be:

```
"tr(INTERNAL_KEY , pk(KEY))"
```

**Comment by aruokhai** [comment]
Hey @louisinger,  can i take this ?
